### ISSUE TITLE
API does not function on accounts with a single device

### ISSUE THREAD

**Issue by evanjd** [sampsyo/wideq#1]
First of all - I'm so grateful you made this!

It looks like there's a bug with wideq where it expects an array of devices at [wideq.py#L395](https://github.com/sampsyo/wideq/blob/master/wideq.py#L395). On an account with a single device, `self.session.get_devices()` returns an object, not an array of objects. Because it assumes an array will be returned, it falls apart after this as it attempts to iterate over the object's keys thinking each key represents a device.

**Comment by sampsyo** [comment]
Got it; thanks! It’s weird that’s allowed to return a single object. Any chance you could contribute a pull request (so you can be sure it works with your setup)?

**Comment by evanjd** [comment]
Done!
