### ISSUE TITLE
ls empty

### ISSUE THREAD

**Issue by alexandr-ushakov-clearscale** [sampsyo/wideq#109]
i connect to api, get oauth 

cat wideq_state.json
```
{
  "model_info": {},
  "gateway": {
    "auth_base": "https://ru.m.lgaccount.com",
    "api_root": "https://ruic.lgthinq.com:46030/api",
    "oauth_root": "https://ru.lgeapi.com",
    "country": "RU",
    "language": "ru-RU"
  },
  "auth": {
    "access_token": "secret",
    "refresh_token": "secret"
  },
  "session": "secret.node_sadap_20",
  "country": "US",
  "language": "en-US"
}
```

But ls is empty
python3 example.py -vvv ls
```
2020-06-26 20:02:27 DEBUG [wideq.example] State file found '/home/pi/git/wideq/wideq_state.json'
2020-06-26 20:02:27 DEBUG [wideq.example] State file found '/home/pi/git/wideq/wideq_state.json'
2020-06-26 20:02:27 DEBUG [wideq.example] Wrote state file '/home/pi/git/wideq/wideq_state.json'
2020-06-26 20:02:27 DEBUG [wideq.example] Wrote state file '/home/pi/git/wideq/wideq_state.json'
```

Help me )

**Comment by stingone** [comment]
Same here. The json file is created with information in it. But as soon i us the ls command nothing happens, no error just executed the example.py without output.

**Comment by stingone** [comment]
Seems to be a v1 - v2 issue? or are both v1 and v2 implemented? https://eic-service.lgthinq.com:46030/v1 gives me a device ID

**Comment by alexandr-ushakov-clearscale** [comment]
Where you put this url? In "api_root" ?

**Comment by stingone** [comment]
> Where you put this url? In "api_root" ?

U used a different repository from gladhorn.. code he wrote is also now being implemented in the v2 pull request they are working on. think we need some patience.

**Comment by alexandr-ushakov-clearscale** [comment]
Oh TY! Realy work
