### ISSUE TITLE
Unable to parse Dryer output

### ISSUE THREAD

**Issue by yoshar1** [sampsyo/wideq#11]
It seems a number of field types that a Dryer returns are not supported:
Both result in an Assert() failure:
AssertionError: unsupported value type Reference
and
AssertionError: unsupported value type Bit

Two sample JSON strings are as follows:
{'type': 'Reference', 'option': ['SmartCourse']}

and

{'type': 'Bit', 'default': '0', 'option': [{'value': 'RemoteStart', 'length': 1, 'default': '0', 'startbit': 0}, {'value': 'EnergySaver', 'length': 1, 'default': '0', 'startbit': 1}, {'value': 'TurboSteam', 'length': 1, 'default': '0', 'startbit': 2}, {'value': 'InitialBit', 'length': 1, 'default': '0', 'startbit': 6}]}

**Comment by sampsyo** [comment]
Hi! This repository only supports AC units. (Pull requests for further device support would be gladly accepted!)
