### ISSUE TITLE
LG Fridge

### ISSUE THREAD

**Issue by VitaliyR** [sampsyo/wideq#12]
Hello!

Thanks for this work!

I've bought LG fridge and using Charles debugged requests from iOS app. 

For settings temperature and express freeze commands it sends next request:

```
('rti/rtiControl', {
  'cmd': 'Control',
  'cmdOpt': 'Set',
  'value': 'ControlData',
  'data': 'Af8BAv////////8='
  'deviceId': device_id,
  'workId': gen_uuid(),
  'format': 'B64',
})
```

Pay attention to data. What kind of format is that? I can't decode it.

As far as I see from **wideq_state.json**, the format of message is correct:

```json
"ControlWifi": {
        "type": "BINARY(BYTE)",
        "action": {
          "SetControl": {
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "ControlData",
            "data": "[{{TempRefrigerator}}, 255, {{IcePlus}}, {{FreshAirFilter}}, 255, 255, 255, 255, 255, 255, 255]"
          }
        }
      }
```

But I can't encode data. Maybe you saw it somewhere while reverse engineering it? 

Thanks!

**Comment by VitaliyR** [comment]
Okay, so it's a bitwise. Thanks :) 

Will add PR with fridge support somewhen.

**Comment by sampsyo** [comment]
Wow, awesome! Good luck fiddling with that binary encoding. :D

No guarantees, but it might be similar to the Base64-encoded data sometimes used for AC monitoring. See the `decode_monitor_binary` function for inspiration.

**Comment by VitaliyR** [comment]
@sampsyo yes, indeed, it is just the same encoding :) Thanks!

**Comment by ncovercash** [comment]
@VitaliyR saw this wasn't implemented yet (as best I could tell); I wrote some code for the related ssut/wideq-js and thought it might be helpful for generating the b64 encoded strings.  Check out ssut/wideq-js#16 – it just iterates through, pulling the variables from the status, and puts it in a byte array which is then converted.
