### ISSUE TITLE
How about union our skills and repositories and create one perfect solution?

### ISSUE THREAD

**Issue by NorDroN** [sampsyo/wideq#14]
Hi!

I found solution https://github.com/wkd8176/wideq where @wkd8176 did great job and create pip package wideq-kr. And also I found a lot of forks where people has been changed language and country. I think we need create parameters for them.

I'd like to integrate my LG devices with HomeKit and I'd like to create package homebridge-wideq.

**Comment by sampsyo** [comment]
It would indeed be great to merge efforts! It sounds like you're not a maintainer of a fork, but I would _love_ to merge functionality from various forks into this main repository. Please open pull requests!

And yes—have you seen #13, where we were just discussing making the country a parameter?

**Comment by rangerek** [comment]
i'd love to see the homebridge plugin - even paypal the creator :D as i have a big headache with AC decision between LG and Gree ;) (2nd one talks to HB)

**Comment by NorDroN** [comment]
I think this is not really an issue, I closed it.
