### ISSUE TITLE
API V2 functional?

### ISSUE THREAD

**Issue by XalaTheShepard** [sampsyo/wideq#141]
Dear all, 

I was wondering whether this project is already functional with the API V2 of Smartthinq. 
It has been some weeks since I last tried to add my LG AC, but they could at that moment not be added to HA, since they used API V2.
Many thanks for keeping for the possible feedback. 

Kind regards, 

Robin

**Comment by blakito** [comment]
Search

https://github.com/sampsyo/wideq/pull/132
