### ISSUE TITLE
How figure out before buy if device is supported (ie v1 or v2)

### ISSUE THREAD

**Issue by elbowz** [sampsyo/wideq#145]
I should buy a washer ([LG ThinQ F4WT409AIDD](https://www.amazon.it/dp/B08DDCNMB9/ref=cm_sw_r_cp_apa_glc_i_8R73F5SFN2PAM6EDQDK0)), but I would like know before buy it, if it's supported (use API v1) or not (use API v2).

Sorry, if the question is already done elsewhere, but I haven't found it.

Thanks for this great project :)

**Comment by MattL0** [comment]
There is no way to know before you try (or ask another user that have the same init) . New appliances are more likely to have v2

**Comment by MattL0** [comment]
By new I mean the date introduced to the market

**Comment by elbowz** [comment]
Thank @MattL0!

More or less is released on august 2020, so quite new I guess.

Are there some feature available only on v2 version or vice versa (eg. Google assistant support or something other), for inference the api version?

For what I read from this project, the support to v2 will be introduced in the future, so in case it was not supported it will be added in the future? Can the v2 support be implemented or is there some technical issue/trouble that don't allow the implementation (eg. encryption, keys, closed protocol)?

Maybe a wiki page with the supported device, feed by users expirience, can be useful?
