### ISSUE TITLE
Status of authenticate() function update in example.py

### ISSUE THREAD

**Issue by RMCob** [sampsyo/wideq#28]
I am sure I saw this discussed previously but I can't find it, so apologies in advance.

I am working on a Homebridge plugin to incorporate the wideq library. It was mentioned somewhere (?) that the authenticate() functionality might be moved into wideq directly if the "Go to this url, type in your login credentials, copy the resultant URL, and paste it here" thing could be done automatically with LG login info that's saved somewhere.

While I understand the concepts, the implementation is WAY above my experience level with GET/POST, etc.

FYI, using the ac-mon example I am already able to display the room temp from my LG AC in a HomeKit temperature sensor button icon. (Low hanging fruit :-)), but only after I have manually logged into the LG site using example.py. 

So.....none of this will work automatically across a reboot unless wideq can log into the LG server automatically when it needs to.  Is anyone (even considering) working on this? Help!

**Comment by sampsyo** [comment]
> It was mentioned somewhere (?) that the authenticate() functionality might be moved into wideq directly if the "Go to this url, type in your login credentials, copy the resultant URL, and paste it here" thing could be done automatically with LG login info that's saved somewhere.

Indeed; this would be pretty tricky—we'd have to do quite a bit of screen-scraping and cookie-tracking to make authentication work. However…

> So.....none of this will work automatically across a reboot unless wideq can log into the LG server automatically when it needs to. Is anyone (even considering) working on this? Help!

I actually think all is not lost! You don't need to store the username & password to make logins persist across reboot. You just need to store the client state. If you save `client.dump()` to a JSON file, as `example.py` does, and reconstitute it, you can get back the same logged-in session you had before—even across reboots!

An even simpler way is how we do it in [the Home Assistant addon](https://github.com/sampsyo/hass-smartthinq), which is to _just_ use the `refresh_token` from the authenticated session. This seems to last for a very long time—I've used one for months (years?) without needing to re-authenticate.

You can see how we get a `Client` object from a token (& country config) here:
https://github.com/sampsyo/hass-smartthinq/blob/871b8a327d1bfb19bf69b96a781b23f1b8144e36/climate.py#L42-L46

**Comment by sampsyo** [comment]
I should also mention that storing a token is also generally considered more secure than storing a username & password. It's actually kind of reassuring to type your password into your browser, pointed to a legitimate `lg.com` domain.

**Comment by gladhorn** [comment]
I assume the answer by @sampsyo  says it all: you only need to do the oauth dance once and then you can get refresh tokens. Closing this, since there is nothing to do, as far as I can tell.
