### ISSUE TITLE
Does anyone know if there is a node.js port of this library yet?

### ISSUE THREAD

**Issue by squareplanetdesign** [sampsyo/wideq#38]
I'm building an automation tool in node.js for my home and wanted to integrate some LG devices into it. I was going to port this library to node.js, but wanted to see if anyone was already working on that before I started.

**Comment by cgilliesrunning** [comment]
Which home automation platform are you using? I am trying to control LG aircon with Homey, I am not a coder by any means but I am hoping that I can get the aircon to read current state and toggle power. This way I can get it integrated into other Homey flows.

**Comment by beele** [comment]
For homekit & homebridge: https://github.com/beele/HomebridgeLgSmartThinqAirco (uses this library as a base)

**Comment by NorDroN** [comment]
@squareplanetdesign, did you find a solution or made your own?

I couldn't find the same library on nodejs and I tried to create my own library ([homebridge-wideq](https://github.com/NorDroN/homebridge-wideq)).
I think [homebridge-wideq](https://github.com/NorDroN/homebridge-wideq) is the same as [HomebridgeLgSmartThinqAirco](https://github.com/beele/HomebridgeLgSmartThinqAirco) and
these libraries have a lot in common, but uses this library as base. I think it's not a good solution, but it works. In my case, I'm using [python-shell](https://www.npmjs.com/package/python-shell) library for running this python scripts on nodejs now.

**Comment by gladhorn** [comment]
I think this is not really an issue for wideq, as such I'd suggest closing it.

**Comment by sampsyo** [comment]
Indeed; I'll close it for now. Feel free to keep discussing Node wrappers in this thread even though it's closed, of course.

**Comment by NorDroN** [comment]
I found solution ([wideq-js](https://github.com/NorDroN/wideq-js)), but it's not full.
I'll try to add more supported devices, but I need people who can test that this library'll work correct with some devices.
And of course I'll rewrite [homebridge-wideq](https://github.com/NorDroN/homebridge-wideq).

**Comment by squareplanetdesign** [comment]
I got air conditioners working off of your wideq-js fork @NorDroN. Thanks for finding this. I opened a pull request against your fork. https://github.com/squareplanetdesign/wideq-js/tree/test_ac_support
