### ISSUE TITLE
link not working after log in

### ISSUE THREAD

**Issue by dodacs** [sampsyo/wideq#4]
After installing the library and running python3 example.py, it is requested to log in the following url:

https://us.m.lgaccount.com/login/sign_in?country=US&language=en-US&svcCode=SVC202&authSvr=oauth2&client_id=LGAO221A02&division=ha&grant_type=password

Once I log in the page I am redirected to the following url which displays "Page not found"

https://us.m.lgaccount.com/login/iabClose/thirdpartylogin?third_party_type=GGL&front_url=https://us.m.lgaccount.com/login/sign_in?country=US&language=en-US&svcCode=SVC202&authSvr=oauth2&client_id=LGAO221A02&onyx_feature=N&division=ha&show_select_country=N&show_add_services=N&oauthTokenExpiredFlag=N&globalFacebook=false&globalGoogle=false&os_type=PC

**Comment by sampsyo** [comment]
Seeing "page not found" is actually expected; the useful information is encoded in the URL. But for me, when I log in via that page, I get sent to this URL:
https://us.m.lgaccount.com/member/iabClose?access_token=REDACTED&refresh_token=REDACTED&oauth2_backend_url=https://us.lgeapi.com/

…with tokens filled in there. Sorry it's not working for you—I don't know what to recommend!

**Comment by radokristof** [comment]
First I had the same issue. You should change region and language if you are outside of US. The accounts also seems to be limited by region, you can't login from 'outside'. So if your account is not created with US region, it won't work with US region

**Comment by Maurotb** [comment]
Same problem, i have modified in wideq.py
COUNRY='IT'
LANGUAGE='it-IT'

https://it.m.lgaccount.com/login/sign_in?svcCode=SVC202&language=it-IT&authSvr=oauth2&grant_type=password&client_id=LGAXXXX&division=ha&country=IT

I login with google and return page not found with url

https://it.m.lgaccount.com/login/iabClose/thirdpartylogin?third_party_type=GGL&front_url=https://it.m.lgaccount.com/login/sign_in?country=IT&language=it-IT&svcCode=SVC202&authSvr=oauth2&client_id=LGAXXXX&onyx_feature=N&division=ha&show_select_country=N&show_add_services=N&oauthTokenExpiredFlag=N&globalFacebook=false&globalGoogle=false&os_type=PC

program return

Traceback (most recent call last):
  File "./example.py", line 176, in <module>
    example(sys.argv[1:])
  File "./example.py", line 157, in example
    client._auth = authenticate(client.gateway)
  File "./example.py", line 19, in authenticate
    return wideq.Auth.from_url(gateway, callback_url)
  File "/usr/local/src/SmartThinQ/wideq/wideq.py", line 253, in from_url
    access_token, refresh_token = parse_oauth_callback(url)
  File "/usr/local/src/SmartThinQ/wideq/wideq.py", line 168, in parse_oauth_callback
    return params['access_token'][0], params['refresh_token'][0]
KeyError: 'access_token'

**Comment by Maurotb** [comment]
Ok problem is google login,
with normal auth (other account) work....
How i can make it work with google auth?

**Comment by sampsyo** [comment]
@Maurotb, your guess is as good as anyone else's! Please look into it and contribute a fix if you find one. We're all just guessing here based on what the servers seem to do; no one working on this actually has any insight "behind the scenes" into what the API is actually _supposed_ to do.
