### ISSUE TITLE
typo on /wideq/client.py

### ISSUE THREAD

**Issue by martinezmp3** [sampsyo/wideq#50]
Terrific job finding this api, im working on a Driver for Hubitat Elevation hub base on this API thanks for the figuring this out, I only can imagine how much work you put in to this I download the the repo and try the example scrip and got an error:

Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import wideq
  File "/home/pi/LGSmart/wideq-master/wideq/__init__.py", line 4, in <module>
    from .client import *  # noqa
  File "/home/pi/LGSmart/wideq-master/wideq/client.py", line 422
    self.model: ModelInfo = client.model_info(device)
              ^
is because a typo on /wideq/client.py
line 422 should say "self.model.ModelInfo = client.model_info(device)"

**Comment by sampsyo** [comment]
Hello! Thanks for the report, but that's not a typo; that's a type annotation. It is [valid syntax](https://www.python.org/dev/peps/pep-0526/) in Python 3.6 and later.
