### ISSUE TITLE
I'm having trouble running the python script on macOS Catalina.

### ISSUE THREAD

**Issue by brsteeve** [sampsyo/wideq#51]
I'm having trouble running the python script on macOS Catalina.

 I am VERY inexperienced with coding and am receiving this message. 

Brennans-MacBook-Pro:wideq Brennan$ python3 example.py -c US -l en-US
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import wideq
  File "/Users/Brennan/Desktop/custom_components/wideq/wideq/__init__.py", line 3, in <module>
    from .core import *  # noqa
  File "/Users/Brennan/Desktop/custom_components/wideq/wideq/core.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Brennans-MacBook-Pro:wideq Brennan$ 

If anyone could help push me in the right direction that would be stellar.

**Comment by sampsyo** [comment]
Hi! TBH this stuff may not quite be ready for non-technical users... but you'll need to `pip install` the module before using it to get its dependencies.

**Comment by Lex-campbell** [comment]
I had a few similar issues on Catalina. I followed this guide and it helped me:

https://github.com/Homebrew/homebrew-core/issues/44996

Basically re-installed python 3 by running `$ brew reinstall -s python`

I then had the same issue as the thread above with the `asn1crypto` package, so i went `$ cd /usr/local/lib/python3.7/site-packages` and deleted anything to do with 'asn1crypto`

Hope it helps

**Comment by gladhorn** [comment]
Thanks for the report. I assume the comments helped, since no follow-up questions were asked. Since this seems not to be an issue with wideq, I'll close it.
