### ISSUE TITLE
Dryer over 14kg in the list?

### ISSUE THREAD

**Issue by idealist33** [sampsyo/wideq#52]
Hi I want to get device list lg thinq dryer over 14kg. but it does not.
My community says that wideq only works old devices which is 9kg dryer using LG Thinq.
Is there any way to use my 14kg dryer in HA? 
Thanks

**Comment by gladhorn** [comment]
I don't think the weight matters. Newer devices use a different API though, work is ongoing, but will take a while before anything is usable.
Is your issue the same as #46?
Currently there is no way to act on this report, please check #46.
