### ISSUE TITLE
adding support for AC Air Flow Mode Change

### ISSUE THREAD

**Issue by kpalczewski** [sampsyo/wideq#59]
Hi,
can you tell me where to look in the code to add some rtiControl values to control airflow of the AC unit?
I have looked in charles proxy in the app requests and they are as follows:
"cmd": "Control",
"cmdOpt": "Set",
"value": (...)

left right swing:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "6",
			"WDirHStep": "100"
		},`

left right blow left:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "6",
			"WDirHStep": "1"
		},`

left right blow right:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "6",
			"WDirHStep": "5"
		},`

up/ down swing:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "100",
			"WDirHStep": "5"
		},`

up down blow up:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "1",
			"WDirHStep": "5"
		},`

up down blow down:
`"value": {
			"Jet": "0",
			"PowerSave": "0",
			"WDirVStep": "6",
			"WDirHStep": "5"
		},`

energy saving:
`value": {
			"Jet": "0",
			"PowerSave": "1",
			"WDirVStep": "1",
			"WDirHStep": "5"
		},`

purification:
`"value": {
			"AirClean": "1"
		},`

**Comment by sampsyo** [comment]
Cool! The place to do this is to add methods to [the `ACDevice` class](https://github.com/sampsyo/wideq/blob/07b6a1ca2131555634e174d9d648380c408dbc5b/wideq/ac.py#L117) that call the `_set_control` method. See the existing methods, such as `set_fan_speed`, that do something similar.

**Comment by kpalczewski** [comment]
I haven't looked at the code before writing this.
I can see that vertical and horizontal support is already in the code ^^
as well as airclean and powersave!
Thanks!
