### ISSUE TITLE
What is the error? DH_KEY_TOO_SMALL

### ISSUE THREAD

**Issue by DenisMtfl** [sampsyo/wideq#60]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eic.lgthinq.com', port=46030): Max retries exceeded with url: /api/member/login (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))

**Comment by sampsyo** [comment]
Sometimes SSL errors can be resolved by upgrading your Python installation. In any case, this is a communication error with the LG servers and not something we can resolve.

**Comment by DenisMtfl** [comment]
I've downgraded the minimal tls version from tls 1.2 to 1.0 in the openssl config.

` /etc/ssl/openssl.cnf`

old:
`MinProtocol = TLSv1.**2** `
new:
`MinProtocol = TLSv1.**0**`

Now it works!

**Comment by OrbitingOcelot** [comment]
Heads up, on Ubuntu 20.04 I was NOT able to fix this using the various posted solutions regarding openssl.conf min TLS version, protocol version, restricted cipher suites etc.

Python always insisted on a DH key exchange which LG servers do not support, they can only do the following ciphers:
AES256-GCM-SHA384
AES128-GCM-SHA256
AES256-SHA256
AES128-SHA256
AES256-SHA
CAMELLIA256-SHA
AES128-SHA
SEED-SHA
CAMELLIA128-SHA

I ended up downloading Ubuntu 18.04 in virtualbox, where the instructions worked out of the box without any messing with the config.
