### ISSUE TITLE
ValueError: unsupported value type String

### ISSUE THREAD

**Issue by dacrypt** [sampsyo/wideq#62]
% python3 example.py -c BR -l pt-BR mon d27c7740-7149-11d3-10b4-7440be9deeb2
Polling...
Polling...
Polling...
- Operation: @AC_MAIN_OPERATION_RIGHT_ON_W
- OpMode: @AC_MAIN_OPERATION_MODE_DRY_W
- WindStrength: @AC_MAIN_WIND_STRENGTH_LOW_W
- TempUnit: NS
- TempCur: 28.5 (0.5-39.5)
- TempCfg: 25 (18-30)
- GroupType: 1
- GroupType: 1 (18-30)
- SleepTime: 0 (30-420)
- OnTime: 0 (0-1440)
- OffTime: 0 (0-1440)
- RacAddFunc: @NON
- ExtraOp: @OFF
- DiagCode: @AC_SMART_DIAGNOSIS_RESULT_NORMAL_S
Traceback (most recent call last):
  File "example.py", line 230, in <module>
    main()
  File "example.py", line 226, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 186, in example
    example_command(client, cmd, args)
  File "example.py", line 162, in example_command
    func(client, *args)
  File "example.py", line 52, in mon
    desc = model.value(key)
  File "/Users/david/dev/unsorted/wideq/wideq/client.py", line 338, in value
    raise ValueError("unsupported value type {}".format(d['type']))
ValueError: unsupported value type String

**Comment by sampsyo** [comment]
Hello! It's pretty hard to say what to do here without more context or understanding how to reproduce the problem. This project is particularly tricky because I only have the LG AC units that I have—I don't have the ability to test or fix things for other models. If you're interested in digging into the code to propose a fix, however, that would be awesome!

In particular, you'll see that that `value` method uses the types of fields that I'm aware of from my testing: enum, range, bit, and reference. I haven't seen the "String" type, and I'd need to see specific API responses including that data to be able to do figure out how to parse it. Since you have such a device, maybe you can help!

**Comment by mstarks01** [comment]
I have an LG fridge and am willing to help if I can. I'm not that well versed in Python yet, but am willing to assist in other ways.

**Comment by gladhorn** [comment]
I suppose the way to fix this would be to catch the exception and give more debug output, so that the original reporter can give us more information.
@dacrypt will you be able to test newer versions of wideq?
@mstarks01 do you have the same issues?

**Comment by gladhorn** [comment]
I pushed a commit that should help us diagnose the problem, please update and run the script again and paste the output here.

**Comment by dacrypt** [comment]
> @dacrypt will you be able to test newer versions of wideq?

With the new version I get:

```
% python3 example.py -c BR -l pt-BR mon d27c7740-7149-11d3-10b4-7440be9deeb2
Traceback (most recent call last):
  File "example.py", line 251, in <module>
    main()
  File "example.py", line 247, in main
    example(args.country, args.language, args.cmd, args.args)
  File "example.py", line 195, in example
    example_command(client, cmd, args)
  File "example.py", line 171, in example_command
    func(client, *args)
  File "example.py", line 40, in mon
    model = client.model_info(device)
  File "/Users/david/dev/dacrypt/wideq/wideq/client.py", line 232, in model_info
    url = device.model_info_url
AttributeError: 'NoneType' object has no attribute 'model_info_url'
```

**Comment by gladhorn** [comment]
Thanks! Seems to be some time information. I pushed yet another update, so that we'll learn the name of the option that we'll then either ignore or handle, could you pull again and post the output? The interesting bit is the ValueError of "mon". The error in ac-config is unrelated, please open a new issue for that so that we can keep track of both issues and don't mix them up. Thanks :)

**Comment by dacrypt** [comment]
```
ValueError: unsupported value name: 'TimeBsOn' type: 'String' data: '{'_comment': '오전 12시 30분은 0030, 오후12시30분은 1230 ,오후 4시30분은 1630 off는 0 ', 'type': 'String'}'
```

**Comment by mstarks01** [comment]
> I suppose the way to fix this would be to catch the exception and give more debug output, so that the original reporter can give us more information.
> @dacrypt will you be able to test newer versions of wideq?
> @mstarks01 do you have the same issues?

I haven't played with the code. It was mentioned that no one had a fridge to develop with, so I was merely offering mine up.

**Comment by gladhorn** [comment]
That change should fix the issue, by ignoring the comment string. I have no idea what TimeBsOn would be - is BS some abbreviation that makes sense to anyone? It clearly is a list of times.

**Comment by dacrypt** [comment]
I have no idea what that is and the message doesn't seem to change at all. Maybe you could just print that out as informational.

The comment translates from Korean "12:30 am 0030, 12:30 pm 1230, 4:30 pm 1630 off 0". It could be some sort of key value dictionary for translating configurations?
12:30am => 00:30
12:30 pm => 12:30
4:30 pm => 16:30
off => 0

**Comment by dacrypt** [comment]
I might have more clues on what Bs could mean. From `wideq_state.json` I can see some references to Bs:

```
          "GetOnTime": {
            "_comment": "GET_켜짐예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "OnTimer"
          },
          "SetOnTime": {
            "_comment": "SET_켜짐예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"OnTimer\":\"{{OnTimer}}\"}"
          },
          "GetOffTime": {
            "_comment": "GET_꺼짐예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "OffTimer"
          },
          "SetOffTime": {
            "_comment": "SET_꺼짐예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"OffTimer\":\"{{OffTimer}}\"}"
          },
          "GetReservationOnTime": {
            "_comment": "GET_켜짐예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "OnTimer"
          },
          "SetReservationOnTime": {
            "_comment": "SET_켜짐예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"OnTime\":\"{{OnTimer}}\"}"
          },
          "GetReservationOffTime": {
            "_comment": "GET_꺼짐예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "OffTimer"
          },
          "SetReservationOffTime": {
            "_comment": "SET_꺼짐예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"OffTime\":\"{{OffTimer}}\"}"
          },
          "GetReservationSleepTime": {
            "_comment": "GET_꺼짐예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "SleepTime"
          },
          "SetReservationSleepTime": {
            "_comment": "SET_취침예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"SleepTime\":\"{{SleepTimer}}\"}"
          },
          "SetReservation": {
            "_comment": "SET_예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"OffTime\":\"{{OffTimer}}\",\"OnTime\":\"{{OnTimer}}\",\"SleepTime\":\"{{SleepTimer}}\"}"
          },
          "GetTimeBsOn": {
            "_comment": "GET_켜짐예약_시각",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "TimeBsOn"
          },
          "SetTimeBsOn": {
            "_comment": "SET_켜짐예약_시각",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"TimeBsOn\":\"{{TimeBsOn}}\"}"
          },
          "GetTimeBsOff": {
            "_comment": "GET_꺼짐예약_시각",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "TimeBsOff"
          },
          "SetTimeBsOff": {
            "_comment": "SET_꺼짐예약_시각",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"TimeBsOff\":\"{{TimeBsOff}}\"}"
          },
          "GetTimeBSReservation": {
            "_comment": "GET_시각예약_꺼짐_켜짐",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "{\"SleepTime\":\"Get\",\"TimeBsOn\":\"Get\",\"TimeBsOff\":\"Get\"}"
          },
          "SetTimeBSReservation": {
            "_comment": "SET_예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"SleepTime\":\"{{SleepTime}}\",\"TimeBsOn\":\"{{TimeBsOn}}\",\"TimeBsOff\":\"{{TimeBsOff}}\"}"
          },
          "GetSchedule": {
            "_comment": "GET_주간예약",
            "cmd": "Control",
            "cmdOpt": "Get",
            "value": "Schedule"
          },
          "SetSchedule": {
            "_comment": "SET_주간예약",
            "cmd": "Control",
            "cmdOpt": "Set",
            "value": "{\"Schedule\":\"{{Schedule}}\"}"
          },
```

From all those, I suspect **Bs** means **Reservation** and there's some information about what "Reservation" is here https://www.manualslib.com/manual/647641/Lg-Air-Conditioner.html?page=17

**Comment by dacrypt** [comment]
@gladhorn seems like you fixed the problem...why don't you create a PR?
