### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by gladhorn** [sampsyo/wideq#68]
Hi,
I was considering adding type annotations (since they make refactoring a lot easier). Currently the tox file has Python 3.4 listed, which makes things a lot harder.
Considering home assistant is on Python 3.7 (I think?), I'd like to propose to bump the minimum Python version to 3.6 or 3.7.
Python 3.6 comes with f-strings, which in my opinion also makes things a lot easier, since it allows very readable string formatting.
Opinions appreciated :)

**Comment by sampsyo** [comment]
Good point! We use the `typing` module already, so I think the 3.4 option was a lie anyway. :smiley: Let's make the minimum 3.6—seems like that will be very unlikely to exclude many systems. I'll make the changes now.
