### ISSUE TITLE
Just bought a new washing machine

### ISSUE THREAD

**Issue by 2016for** [sampsyo/wideq#8]
Do you think we can figure out a way to get it to work with this?
Thanks.

If this works my then next step would be to work on a Home Assistant Custom Component.

**Comment by salanki** [comment]
I have it working with my LG washer dryer combo.

**Comment by 2016for** [comment]
Awesome! That's great news.
Do I need to do anything for it to work or it should be straightforward.

Would really appreciate if you could share ho you're using it right now and how you made it work.

I also bought a washer/dryer combo.
Will be installing the machine today! Already excited.

**Comment by dpyy** [comment]
Can you let us know what you can do with the washer/dryer combo from this library?

**Comment by maileys** [comment]
Hi Guys,

I have a washer dryer combo and run homeassistant, I am going to look at this code and see if I can get basic devise status returned

**Comment by altryne** [comment]
Have washer / dryer as well. Would love to see their status somehow in Home Assistant

**Comment by mrcasablr** [comment]
@salanki could you share your code?

**Comment by gladhorn** [comment]
Please refer to the readme to get started. https://github.com/sampsyo/wideq/blob/master/README.md
In addition to this, you'll want the home assistant component which depends on wideq. So you may want to start looking there. This thread is not really an issue with wideq and can probably be closed. When you run into trouble, please open specific issues describing what doesn't work. See also https://github.com/sampsyo/hass-smartthinq .
Thanks :)
