### ISSUE TITLE
HOME ASSISTANT COMMUNITY STORE (HACS)

### ISSUE THREAD

**Issue by Xitro01** [sampsyo/wideq#85]
Very nice add-on, have used it without any problems so far. So great job and thanks a lot for all your time spend on this.

I have just a small feature request, to have this add-on added to the HOME ASSISTANT COMMUNITY STORE (HACS). So that we can easily stay up-to-date with the latest version!

https://hacs.xyz/docs/publish/start

**Comment by sampsyo** [comment]
Hi! Please see https://github.com/sampsyo/hass-smartthinq/pull/36.
