### ISSUE TITLE
authentication seems to work, but ls returns nothing?

### ISSUE THREAD

**Issue by honestbleeps** [sampsyo/wideq#86]
I'm assuming based on the documentation that the steps are:

`python3 example.py -c US -l en-US`

log in and get that redirect URL as asked -- paste into the output -- it closes, seeming to save my auth info.

then, I run:

`python3 example.py ls` -- but nothing happens, no error, no output.

It seems from my guessing at syntax that I've got it right (if I try a different command, I properly get an error that it's an invalid command), but I'm not getting anything listed.  I should be seeing a Washer and a Dryer... and maybe a TV also.

Any assistance on debugging / logging to help do so would be appreciated!

**Comment by sampsyo** [comment]
Sounds like things are working, but sadly the API is just reporting zero devices on your account. Which is likely the problem #46, in which LG has moved to a new API for some users & devices.

**Comment by honestbleeps** [comment]
oh, gotcha! I just looked for that api2 branch, though, and it appears to be gone?

**Comment by sampsyo** [comment]
I believe that's in someone else's fork, although I could be wrong?

**Comment by honestbleeps** [comment]
nope, you're right. I'm getting over a cold and still a bit dense. I noticed immediately after revisiting the thread, sorry! I'll close this.
