### ISSUE TITLE
Question regarding internet connection.

### ISSUE THREAD

**Issue by Xenobreaker** [sampsyo/wideq#87]
Does wideq need to have a constant internet connection to LG servers to control devices after initial device setup? Thanks!

**Comment by sampsyo** [comment]
Yep! It works by contacting LG's API, not via the local network.

**Comment by Xenobreaker** [comment]
Okay thanks!

**Comment by mck182** [comment]
@sampsyo out of curiosity - is there any plan
and/or ongoing work (even elsewhere) to talk
to the devices directly over local network? is
that even possible?

**Comment by sampsyo** [comment]
I haven't found a way, although I've looked a little bit. It would certainly be a fun project to see if some more hardcore network interception could reveal anything useful—I haven't been able to find anything unencrypted yet.
