### ISSUE TITLE
How to use the commands

### ISSUE THREAD

**Issue by ltai0001** [sampsyo/wideq#9]
I am relatively new to python but would love to use your script
I did run the example.py through the python IDE by loading the file and executing the "Run" command from the IDE menu - It gave me the prompt through the python shell for the URL then it rendered what I believe is the key telling me this is a refrigerator signature...
all seems good but then I dont know what to do :)

any hint would be very appreciated -

**Comment by sampsyo** [comment]
I don't know how to use the included Python IDE; sorry! I hate to say it, but if you're not comfortable with Python programming or the command line, this software might not be for you. It's really just a library that's meant for other people to build real applications out of. Sorry about that!
